services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    restart: always

  streamlit:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000/predict
    restart: always
    depends_on:
      - fastapi
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./monitoring/Grafana/dashboards:/etc/grafana/dashboards
      - ./monitoring/Grafana/provisioning:/etc/grafana/provisioning
      
  traffic:
    build: .
    container_name: traffic
    command: python scripts/traffic.py
    depends_on:
      - fastapi
    environment:
      - API_URL=http://fastapi:8000/predict
