import pytest
import json
import os
from pathlib import Path

# -----------------------------
# CONFIGURATION
# -----------------------------
METADATA_PATH = Path("models/metadata.json")

# Define minimum acceptable performance thresholds
# These are slightly lower than your current run (0.98) to allow for 
# minor variance while catching major regressions.
THRESHOLDS = {
    "accuracy": 0.90,
    "f1": 0.85,
    "precision": 0.85,
    "recall": 0.80
}

# The exact features the API and Preprocessor expect
EXPECTED_FEATURES = [
    "Age",
    "Gender",
    "Support Calls",
    "Payment Delay",
    "Total Spend",
    "Last Interaction"
]

# -----------------------------
# FIXTURES
# -----------------------------
@pytest.fixture
def model_metadata():
    """Load the metadata generated by the training script."""
    if not METADATA_PATH.exists():
        pytest.fail(f"Metadata file not found at {METADATA_PATH}. Run training first.")
    
    with open(METADATA_PATH, "r") as f:
        return json.load(f)

# -----------------------------
# TEST CASES
# -----------------------------

def test_metadata_structure(model_metadata):
    """Verify that metadata contains all required MLOps fields."""
    required_keys = ["version", "timestamp", "metrics", "feature_names", "mlflow_run_id"]
    for key in required_keys:
        assert key in model_metadata, f"Missing required key: {key}"


def test_model_performance_thresholds(model_metadata):
    """
    Quality Gate: Check if model metrics meet the minimum requirements.
    This prevents 'garbage' models from being deployed.
    """
    metrics = model_metadata["metrics"]
    
    for metric_name, threshold in THRESHOLDS.items():
        actual_value = metrics.get(metric_name)
        assert actual_value is not None, f"Metric {metric_name} not found in metadata"
        assert actual_value >= threshold, (
            f"Model {metric_name} is {actual_value:.4f}, "
            f"which is below the threshold of {threshold}"
        )


def test_feature_consistency(model_metadata):
    """
    Ensure the features used during training match the expected API schema.
    This prevents 'Feature Mismatch' errors in production.
    """
    trained_features = model_metadata["feature_names"]
    
    # Check if sets match (order doesn't matter for logic, but names do)
    assert set(trained_features) == set(EXPECTED_FEATURES), (
        f"Feature mismatch! \nExpected: {EXPECTED_FEATURES}\nActual: {trained_features}"
    )


def test_model_file_exists():
    """Verify that the actual model binary was saved alongside metadata."""
    model_path = Path("models/model.pkl")
    assert model_path.exists(), "model.pkl binary is missing in models/ directory"


def test_latest_version_pointer():
    """Verify that the LATEST_VERSION.txt was updated correctly."""
    pointer_path = Path("models/LATEST_VERSION.txt")
    assert pointer_path.exists(), "LATEST_VERSION.txt is missing"
    
    version_text = pointer_path.read_text().strip()
    assert version_text.startswith("run_"), f"Invalid version format in pointer: {version_text}"