apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: churn-app
resources:
  - namespace.yaml
  - grafana-secret.yaml      
  - prometheus-pvc.yaml
  - fastapi-hpa.yaml
  - fastapi-deployment.yaml
  - fastapi-service.yaml
  - streamlit-deployment.yaml
  - streamlit-service.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - ingress.yaml
  - traffic.yaml
# generatorOptions:
#   disableNameSuffixHash: true
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=monitoring/prometheus.yml
  - name: grafana-config
    files:
      - datasource.yml=monitoring/grafana/provisioning/datasources/datasource.yml
      - dashboard.yml=monitoring/grafana/provisioning/dashboards/dashboard.yml
      - churn_dashboard.json=monitoring/grafana/dashboards/churn_dashboard.json
