apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-ui
  namespace: churn-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: churn-ui
  template:
    metadata:
      labels:
        app: churn-ui
    spec:
      containers:
        - name: churn-ui
          image: tobichngoc/churn-ui:v1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          env:
            - name: API_URL
              value: http://churn-api:8000
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            failureThreshold: 18
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
